#!/usr/bin/env bash
#
# install-windows-loader.sh — generate the Windows-side WezTerm loader from WSL.
#
# WezTerm runs as a Windows app and only reads C:\Users\<you>\.wezterm.lua. This
# script writes that loader so it points back at the version-controlled config in
# this repo, deriving every machine-specific value automatically:
#   - Windows home  : from cmd.exe's %USERPROFILE%, via wslpath
#   - WSL distro     : from $WSL_DISTRO_NAME
#   - repo UNC path  : from this script's own location
#
# Idempotent: re-run any time. An existing loader is backed up once to
# .wezterm.lua.bak before being overwritten.

set -euo pipefail

# ── Sanity: must be inside WSL ───────────────────────────────────────────────
if ! grep -qiE '(microsoft|wsl)' /proc/version 2>/dev/null; then
  echo "error: this script only makes sense inside WSL." >&2
  exit 1
fi

distro="${WSL_DISTRO_NAME:-}"
if [[ -z "$distro" ]]; then
  echo "error: \$WSL_DISTRO_NAME is empty; cannot determine the distro name." >&2
  exit 1
fi

# ── Resolve the repo config path (relative to this script) ───────────────────
script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
repo_config="$script_dir/.config/wezterm/wezterm.lua"
if [[ ! -f "$repo_config" ]]; then
  echo "error: repo config not found at $repo_config" >&2
  exit 1
fi

# WSL path -> Windows UNC path: \\wsl.localhost\<distro>\path\with\backslashes
# (older Windows builds use \\wsl$\ instead — swap in the generated file if needed)
unc_path="\\\\wsl.localhost\\${distro}${repo_config//\//\\}"

# ── Locate the Windows home directory ────────────────────────────────────────
win_userprofile="$(cmd.exe /C 'echo %USERPROFILE%' 2>/dev/null | tr -d '\r')"
if [[ -z "$win_userprofile" || "$win_userprofile" == *'%USERPROFILE%'* ]]; then
  echo "error: could not read %USERPROFILE% from cmd.exe." >&2
  exit 1
fi
win_home="$(wslpath -u "$win_userprofile")"
if [[ ! -d "$win_home" ]]; then
  echo "error: resolved Windows home does not exist: $win_home" >&2
  exit 1
fi

loader="$win_home/.wezterm.lua"

# ── Back up any pre-existing loader once ─────────────────────────────────────
if [[ -f "$loader" && ! -f "$loader.bak" ]]; then
  cp "$loader" "$loader.bak"
  echo "backed up existing loader -> $loader.bak"
fi

# ── Write the loader ─────────────────────────────────────────────────────────
cat > "$loader" <<EOF
-- .wezterm.lua — Windows-side loader.
--
-- GENERATED by wezterm/install-windows-loader.sh — do not edit by hand.
-- Re-run that script to regenerate. Edit the real config in the dotfiles repo:
--   $repo_config
--
-- This delegates to the version-controlled config over the WSL mount and
-- registers it for hot-reload. If your Windows build uses the legacy mount,
-- swap \\\\wsl.localhost\\ for \\\\wsl\$\\ below.

local wezterm = require 'wezterm'

-- Machine-specific value baked in at generation time so the shared config can
-- pick the right WSL domain without hard-coding the distro.
wezterm.GLOBAL = wezterm.GLOBAL or {}
wezterm.GLOBAL.wsl_distro = '$distro'

local repo_config = [[$unc_path]]

wezterm.add_to_config_reload_watch_list(repo_config)
return dofile(repo_config)
EOF

echo "wrote loader -> $loader"
echo "  distro     : $distro"
echo "  repo config: $repo_config"
echo "  UNC path   : $unc_path"
